### ISSUE TITLE
closure bug

### ISSUE THREAD

**Issue by vinarius** [vinarius/Free-Code-Camp#1]
As an authenticated user on the /user/dashboard route:

I go to search for a poll (I've been using favorite food as test data).
The client side javascript creates the graph and is supposed to create buttons for every dataset available and add an eventlistener for each button, but the event listeners only get attached to the first button instead of each accordingly.

**Comment by MohammadHasham** [comment]
can you post that button code snippet here?

**Comment by vinarius** [comment]
Sure, this code was taken from
The issue is in the for loop where it is appending the buttons and adding the event listeners.

    pollForm.addEventListener('submit', (e) => {
        e.preventDefault();
        let pollName = $("#formInputName").val().toLowerCase().split(' ').join('');
        $.ajax({
            type: 'POST',
            url: '/api/pollData',
            data: {
                pollName: pollName
            },
            success: (data) => {
                for (let i = 0; i < data.datasets.length; i++) {
                    (function(){
                        appendVoteOptionBtn(data.datasets[i].label);
                        let voteOptionButton = document.querySelector('#voteOptionsBtn' + voteOptions.length);
                        voteOptionButton.addEventListener('click', myListenerTest('#voteOptionsBtn' + voteOptions.length, data.datasets[i].label), false);
                        // document.querySelector('#voteOptionsBtn' + voteOptions.length).addEventListener('click', myListenerTest('#voteOptionsBtn' + voteOptions.length, data.datasets[i].label), false);
                        addVoteListener('#voteOptionsBtn' + voteOptions.length, data.datasets[i].label);
                        addRemoveDatasetListener('#removeDatasetBtn' + voteOptions.length);
                    }());
                    voteData.push(data.datasets[i].count);
                    labelData.push(data.datasets[i].label);
                }
                createChart(voteData, labelData);
                currentPoll = pollName;
            },
            error: (err) => {
                console.error("Error sending post with poll name.");
                console.error(err);
            }
        });
    });

    function appendVoteOptionBtn(datasetName) {
        $("#voteOptionsContainer").append('<div class="d-flex flex-row voteButtonContainer"><button class="voteOption btn btn-success" id="voteOptionsBtn' + voteOptions.length + '">' + datasetName + '</button><button id="removeDatasetBtn' + voteOptions.length + '" class="removeDatasetBtn btn btn-dark">X</button></div>');
    }

**Comment by vinarius** [comment]
Issue has been fixed. The id's were not being correctly assigned and each dataset button had the same id, because nothing was pushed to the voteOptions global variable during the for loop.

**Comment by MohammadHasham** [comment]
That's good :-)
